### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rtzoeller** [digidotcom/python-suitcase#44]
It's been about 11 months since the last release, and Suitcase has gained quite a few features and fixes, including:

* `FieldArray` now works properly when empty and supports a number of elements provider
* `SubstructureField`s can be wrapped in `ConditionalField`s
* Exceptions which are reraised contain the original message
* Keyword initialization of `Structure`s is now supported

IMO Suitcase is due for a `0.10` release.

**Comment by DrASK** [comment]
SOunds good to me. I wonder what @posborne thinks.

**Comment by posborne** [comment]
Sorry for the delay.  Yes, I can push a new update to pypi.

**Comment by posborne** [comment]
Version 0.10.2 is now released and the changelog has been updated.  The reason for the ".2" at the end is because I messed up the markdown -> rst readme conversion a couple of times and you need to upload a new version to fix.  Oh, well.

* https://pypi.python.org/pypi/suitcase/0.10.2
* https://github.com/digidotcom/python-suitcase/blob/master/CHANGELOG.md#010--2016-10-2016
